-- ============================================================
-- Tahap 12: Product & Country Performance
-- Product : revenue, quantity, orders containing product,
--           customers, ASP, product concentration,
--           high-AOV product presence
-- Country : revenue, orders, customers, AOV, absolute vs
--           relative performance, volume vs AOV matrix
-- DoD: breakdown reconcile ke total locked KPI (Tahap 6)
-- Status : ⬜ belum mulai
-- ============================================================
