-- ============================================================
-- Tahap 13: AOV Drivers & Revenue Decomposition
-- Candidate dimensions: basket size, average item value,
--   customer segment, purchase frequency, product mix,
--   country, month/period
-- Methods: grouped comparison, distributions, percentiles,
--   contribution, correlation, optional descriptive regression
-- Batasan: seluruh analisis observasional -- gunakan
--   "associated with / correlated with / tends to occur with",
--   HINDARI "caused by / resulted in / led to / proved that"
-- DoD: breakdown reconcile ke total locked KPI (Tahap 6);
--      tidak ada bahasa kausal di finding
-- Status : ⬜ belum mulai
-- ============================================================
